### ISSUE TITLE
expected hoisted manifest

### ISSUE THREAD

**Issue by productdevbook** [fatihsolhan/v-onboarding#11]
yarn lock delete and yarn install

error An unexpected error occurred: "expected hoisted manifest for \"v-onboarding#vue#@vue/server-renderer#@vue/compiler-ssr\"".

```
Yarn version: 
  1.22.17

Node version: 
  16.13.2

Platform: 
  linux x64

Trace: 
  Invariant Violation: expected hoisted manifest for "v-onboarding#vue#@vue/server-renderer#@vue/compiler-ssr"
      at invariant (/usr/share/yarn/lib/cli.js:2314:15)
      at _loop2 (/usr/share/yarn/lib/cli.js:95100:9)
      at PackageHoister.init (/usr/share/yarn/lib/cli.js:95170:19)
      at PackageLinker.getFlatHoistedTree (/usr/share/yarn/lib/cli.js:48922:20)
      at PackageLinker.<anonymous> (/usr/share/yarn/lib/cli.js:48933:27)
      at Generator.next (<anonymous>)
      at step (/usr/share/yarn/lib/cli.js:310:30)
      at /usr/share/yarn/lib/cli.js:328:14
      at new Promise (<anonymous>)
      at new F (/usr/share/yarn/lib/cli.js:5301:28)
```

**Comment by fatihsolhan** [comment]
Hi @productdevbook 

The problem is that your yarn.lock file is out of date.
Can you try this solution: https://stackoverflow.com/a/66417378/7971182

**Comment by productdevbook** [comment]
yes, iam yarn.lock delete and yarn install is problem. :)

**Comment by fatihsolhan** [comment]
Does `yarn install` work correctly when you remove `v-onboarding` from your dependencies?

**Comment by productdevbook** [comment]
hmm interested no fixed, different library now problem. Thank you

**Comment by productdevbook** [comment]
`yarn cache clean` run, `yarn.lock` delete and yarn install fixed
