### ISSUE TITLE
Vue app is crashing. Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by pedropcamellon** [fatihsolhan/v-onboarding#89]
**Describe the bug**
Vue app is crashing due to this error.

```
v-onboarding.es.js:903  Uncaught TypeError: Object(...) is not a function
    at Module.eval (v-onboarding.es.js:903:1)
    at eval (v-onboarding.es.js:1148:30)
    at ./node_modules/v-onboarding/dist/v-onboarding.es.js (chunk-vendors.js:30600:1)
    at __webpack_require__ (app.js:849:30)
    at fn (app.js:151:20)
    at eval (cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/ts-loader/index.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/@vue/cli-service/node_modules/vue-loader/dist/index.js?!./src/modules/home/entityCard/views/EntityCardNegotiation.vue?vue&type=script&lang=ts:63:71)
    at ./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/ts-loader/index.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/@vue/cli-service/node_modules/vue-loader/dist/index.js?!./src/modules/home/entityCard/views/EntityCardNegotiation.vue?vue&type=script&lang=ts (app.js:12339:1)
    at __webpack_require__ (app.js:849:30)
    at fn (app.js:151:20)
    at eval (EntityCardNegotiation.vue:1:1)
```

**To Reproduce**
1. Install `npm install v-onboarding`
2. Follow instructions for [basic example](https://v-onboarding-docs.fatihsolhan.com/examples/basic)
4. See error in console.

**Expected behavior**
App should not crash.

**Screenshots**
![image](https://github.com/fatihsolhan/v-onboarding/assets/83567517/8484f6b7-e7d2-497e-a446-1299775d64ec)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 119

**Comment by fatihsolhan** [comment]
Hey @pedropcamellon, can you please let me know what is your vue version?

**Comment by pedropcamellon** [comment]
Sure! 

"dependencies": {
    "@apollo/client": "^3.8.7",
    "@vue/apollo-option": "^4.0.0-beta.9",
    "animate.css": "^4.1.1",
    "axios": "0.21.1",
    "bootstrap": "4.6.0",
    "core-js": "3.8.2",
    "font-awesome": "4.7.0",
    "graphql": "^16.8.1",
    "graphql-tag": "^2.12.6",
    "hammerjs": "^2.0.8",
    "inter-ui": "3.15.0",
    "jquery": "3.5.1",
    "js-cookie": "2.2.1",
    "moment": "2.29.1",
    "moment-timezone": "0.5.33",
    "normalize.css": "8.0.1",
    "noty": "^3.2.0-beta-deprecated",
    "popper.js": "1.16.1",
    "secure-ls": "1.2.6",
    "uuid-random": "^1.3.2",
    "vue": "~3.0.4",
    "vue-google-charts": "^1.1.0",
    "vue-i18n": "9.0.0",
    "vue-loader": "^17.2.2",
    "vue-router": "4.0.3",
    "vue-shepherd": "^3.0.0",
    "vue-template-compiler": "2.6.12",
    "vue3-blocks-tree": "^0.6.1",
    "vue3-google-map": "^0.15.0",
    "vue3-tel-input": "1.0.4",
    "vuex": "4.0.0",
    "vuex-persistedstate": "4.0.0-beta.3",
    "webpack": "4.46.0"
  },
  "devDependencies": {
    "@playwright/test": "^1.35.1",
    "@types/js-cookie": "2.2.6",
    "@typescript-eslint/eslint-plugin": "4.13.0",
    "@typescript-eslint/parser": "4.13.0",
    "@volar-plugins/prettier": "^1.1.4",
    "@volar-plugins/vetur": "^0.1.0",
    "@volar/vue-language-plugin-pug": "^1.0.1",
    "@vue/cli-plugin-babel": "5.0.0-alpha.2",
    "@vue/cli-plugin-typescript": "5.0.0-alpha.2",
    "@vue/cli-service": "5.0.0-alpha.2",
    "@vue/compiler-sfc": "3.0.5",
    "@vue/eslint-config-standard": "6.0.0",
    "@vue/eslint-config-typescript": "7.0.0",
    "cross-env": "^7.0.3",
    "dotenv": "^16.0.2",
    "eslint": "7.17.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-node": "11.1.0",
    "eslint-plugin-promise": "4.2.1",
    "eslint-plugin-vue": "7.4.1",
    "http-server": "^14.1.1",
    "npm-run-all": "^4.1.5",
    "pug": "3.0.0",
    "pug-plain-loader": "1.1.0",
    "sass": "1.32.4",
    "sass-loader": "8.0.2",
    "typescript": "~4.5"
  },

**Comment by fatihsolhan** [comment]
Thank you but unfortunately I couldn't reproduce the issue. Can you please reproduce it on codesandbox or stackblitz?

**Comment by fatihsolhan** [comment]
Closing due to inactivity. Feel free to reopen with reproduction of the issue on codesandbox or similar platforms.
